### ISSUE TITLE
[Idea] Agregar módulo para entender errores

### ISSUE THREAD

**Issue by durancristhian** [javascript-101/javascript-101#12]
Estaría bueno darle un marco de módulo (quizás después del módulo 1) a entender errores, tener un ejemplo de código que muestre uno y enseñar a leer la descripción, donde está y a interpretar la línea de código donde se generó.

Esto me parece de vital importancia porque siempre lo explicamos a medida que se va preguntando cuando ya varios tuvieron el mismo problema. Para mi es un tema básico.

**Comment by nhsz** [comment]
Resuelto con el ejercicio de [errores comunes](https://github.com/javascript-101/javascript-101/blob/master/ejercicios/conceptuales/02.md)
